/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JLabel;

/**
 *
 * @author End_You
 */
public class VentanaEFinJuego extends javax.swing.JFrame {

    /**
     * Creates new form VistaFinJuego
     */
    public VentanaEFinJuego() {
        initComponents();
        setLocationRelativeTo(null);//Centramos el formulario
        setResizable(false);
    }

    public JLabel getLblAverageE1() {
        return lblAverageE1;
    }

    public JLabel getLblAverageE2() {
        return lblAverageE2;
    }

    public JLabel getLblCarreraE1() {
        return lblCarreraE1;
    }

    public JLabel getLblCarreraE2() {
        return lblCarreraE2;
    }

    public JLabel getLblDobleE2() {
        return lblDobleE2;
    }

    public JLabel getLblDoblesE1() {
        return lblDoblesE1;
    }

    public JLabel getLblErroresE1() {
        return lblErroresE1;
    }

    public JLabel getLblErroresE2() {
        return lblErroresE2;
    }

    public JLabel getLblHitsE1() {
        return lblHitsE1;
    }

    public JLabel getLblHitsE2() {
        return lblHitsE2;
    }

    public JLabel getLblHomerunE1() {
        return lblHomerunE1;
    }

    public JLabel getLblHomerunE2() {
        return lblHomerunE2;
    }

    public JLabel getLblTripleE2() {
        return lblTripleE2;
    }

    public JLabel getLblTriplesE1() {
        return lblTriplesE1;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblCarreraE1 = new javax.swing.JLabel();
        lblHitsE2 = new javax.swing.JLabel();
        lblDobleE2 = new javax.swing.JLabel();
        lblTripleE2 = new javax.swing.JLabel();
        lblHomerunE2 = new javax.swing.JLabel();
        lblErroresE2 = new javax.swing.JLabel();
        lblAverageE2 = new javax.swing.JLabel();
        lblHitsE1 = new javax.swing.JLabel();
        lblDoblesE1 = new javax.swing.JLabel();
        lblTriplesE1 = new javax.swing.JLabel();
        lblHomerunE1 = new javax.swing.JLabel();
        lblErroresE1 = new javax.swing.JLabel();
        lblAverageE1 = new javax.swing.JLabel();
        lblCarreraE2 = new javax.swing.JLabel();
        fondoAlineacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(226, 156, 0));
        jButton1.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Continuar");
        jButton1.setBorder(null);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 130, 40));

        lblCarreraE1.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblCarreraE1.setForeground(new java.awt.Color(255, 255, 255));
        lblCarreraE1.setText("0");
        jPanel1.add(lblCarreraE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 20, 30));

        lblHitsE2.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblHitsE2.setForeground(new java.awt.Color(255, 255, 255));
        lblHitsE2.setText("0");
        jPanel1.add(lblHitsE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 20, 30));

        lblDobleE2.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblDobleE2.setForeground(new java.awt.Color(255, 255, 255));
        lblDobleE2.setText("0");
        jPanel1.add(lblDobleE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 20, 30));

        lblTripleE2.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblTripleE2.setForeground(new java.awt.Color(255, 255, 255));
        lblTripleE2.setText("0");
        jPanel1.add(lblTripleE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 20, 30));

        lblHomerunE2.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblHomerunE2.setForeground(new java.awt.Color(255, 255, 255));
        lblHomerunE2.setText("0");
        jPanel1.add(lblHomerunE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 20, 30));

        lblErroresE2.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblErroresE2.setForeground(new java.awt.Color(255, 255, 255));
        lblErroresE2.setText("0");
        jPanel1.add(lblErroresE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 20, 30));

        lblAverageE2.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblAverageE2.setForeground(new java.awt.Color(255, 255, 255));
        lblAverageE2.setText("0");
        jPanel1.add(lblAverageE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 20, 30));

        lblHitsE1.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblHitsE1.setForeground(new java.awt.Color(255, 255, 255));
        lblHitsE1.setText("0");
        jPanel1.add(lblHitsE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 20, 30));

        lblDoblesE1.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblDoblesE1.setForeground(new java.awt.Color(255, 255, 255));
        lblDoblesE1.setText("0");
        jPanel1.add(lblDoblesE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 20, 30));

        lblTriplesE1.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblTriplesE1.setForeground(new java.awt.Color(255, 255, 255));
        lblTriplesE1.setText("0");
        jPanel1.add(lblTriplesE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 20, 30));

        lblHomerunE1.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblHomerunE1.setForeground(new java.awt.Color(255, 255, 255));
        lblHomerunE1.setText("0");
        jPanel1.add(lblHomerunE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 20, 30));

        lblErroresE1.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblErroresE1.setForeground(new java.awt.Color(255, 255, 255));
        lblErroresE1.setText("0");
        jPanel1.add(lblErroresE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 20, 30));

        lblAverageE1.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblAverageE1.setForeground(new java.awt.Color(255, 255, 255));
        lblAverageE1.setText("0");
        jPanel1.add(lblAverageE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 20, 30));

        lblCarreraE2.setFont(new java.awt.Font("Machine BT", 0, 18)); // NOI18N
        lblCarreraE2.setForeground(new java.awt.Color(255, 255, 255));
        lblCarreraE2.setText("0");
        jPanel1.add(lblCarreraE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 20, 30));

        fondoAlineacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plantillaFinJuego.png"))); // NOI18N
        jPanel1.add(fondoAlineacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 700, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Controller.FinJuegoController.eventoBotonContinuar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEFinJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEFinJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoAlineacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAverageE1;
    private javax.swing.JLabel lblAverageE2;
    private javax.swing.JLabel lblCarreraE1;
    private javax.swing.JLabel lblCarreraE2;
    private javax.swing.JLabel lblDobleE2;
    private javax.swing.JLabel lblDoblesE1;
    private javax.swing.JLabel lblErroresE1;
    private javax.swing.JLabel lblErroresE2;
    private javax.swing.JLabel lblHitsE1;
    private javax.swing.JLabel lblHitsE2;
    private javax.swing.JLabel lblHomerunE1;
    private javax.swing.JLabel lblHomerunE2;
    private javax.swing.JLabel lblTripleE2;
    private javax.swing.JLabel lblTriplesE1;
    // End of variables declaration//GEN-END:variables
}
