/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import static Controller.NuevoEquipoController.ventana;
import Model.Conexion;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.ResultSet;
import View.VistaJugar;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author End_You
 */
public class VistaNuevoEquipo extends javax.swing.JFrame {

    /**
     * Creates new form VistaNuevoEquipo
     */
    public VistaNuevoEquipo() {
        initComponents();
        setLocationRelativeTo(null);//Centramos el formulario
        setResizable(false);
       
    }

    public JComboBox<String> getCboxPosicion() {
        return CboxPosicion;
    }

    public void setCboxPosicion(JComboBox<String> CboxPosicion) {
        this.CboxPosicion = CboxPosicion;
    }

    public JComboBox<String> getCboxBateadores() {
        return CboxBateadores;
    }

    public void setCboxBateadores(JComboBox<String> CboxBateadores) {
        this.CboxBateadores = CboxBateadores;
    }

    public JComboBox<String> getCboxPitchers() {
        return CboxPitchers;
    }

    public void setCboxPitchers(JComboBox<String> CboxPitchers) {
        this.CboxPitchers = CboxPitchers;
    }

    public JButton getBtnIngresarEquipo() {
        return btnIngresarEquipo;
    }

    public JButton getBtnIngresarJugador() {
        return btnIngresarJugador;
    }

    public JTextField getTxtNombreEquipo() {
        return txtNombreEquipo;
    }

    public JTextField getTxtNombreJugador() {
        return txtNombreJugador;
    }

    public JTextField getTxtNumeroJugador() {
        return txtNumeroJugador;
    }

    public JTextField getTxtProvincia() {
        return txtProvincia;
    }
    
 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnIngresarEquipo = new javax.swing.JButton();
        btnIngresarJugador = new javax.swing.JButton();
        txtProvincia = new javax.swing.JTextField();
        txtNombreJugador = new javax.swing.JTextField();
        txtNumeroJugador = new javax.swing.JTextField();
        txtNombreEquipo = new javax.swing.JTextField();
        CboxPosicion = new javax.swing.JComboBox<>();
        CboxBateadores = new javax.swing.JComboBox<>();
        CboxPitchers = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setBackground(new java.awt.Color(226, 156, 0));
        btnAtras.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("< Atras");
        btnAtras.setBorder(null);
        btnAtras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 170, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconoNuevoEquipo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 330, 70));

        btnEliminar.setBackground(new java.awt.Color(226, 156, 0));
        btnEliminar.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 170, 50));

        btnGuardar.setBackground(new java.awt.Color(44, 178, 0));
        btnGuardar.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.setEnabled(false);
        btnGuardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 210, 53));

        btnIngresarEquipo.setBackground(new java.awt.Color(226, 156, 0));
        btnIngresarEquipo.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        btnIngresarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarEquipo.setText("+ Ingresar");
        btnIngresarEquipo.setBorder(null);
        btnIngresarEquipo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIngresarEquipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIngresarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarEquipoActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 110, 30));

        btnIngresarJugador.setBackground(new java.awt.Color(226, 156, 0));
        btnIngresarJugador.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        btnIngresarJugador.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarJugador.setText("+ Ingresar");
        btnIngresarJugador.setBorder(null);
        btnIngresarJugador.setEnabled(false);
        btnIngresarJugador.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIngresarJugador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIngresarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarJugadorActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 210, 50));

        txtProvincia.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        txtProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProvinciaActionPerformed(evt);
            }
        });
        jPanel1.add(txtProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 190, 30));

        txtNombreJugador.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        txtNombreJugador.setEnabled(false);
        txtNombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreJugadorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 190, 30));

        txtNumeroJugador.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        txtNumeroJugador.setEnabled(false);
        txtNumeroJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroJugadorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumeroJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 190, 30));

        txtNombreEquipo.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        txtNombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEquipoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 190, 30));

        CboxPosicion.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        CboxPosicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugador de Cuadro", "Jardinero", "Receptor", "Pitcher" }));
        CboxPosicion.setEnabled(false);
        CboxPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxPosicionActionPerformed(evt);
            }
        });
        jPanel1.add(CboxPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 250, -1));

        CboxBateadores.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        CboxBateadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bateador de Fuerza", "Bateador de Tacto", "Bateador de Bajo Rendimiento" }));
        CboxBateadores.setEnabled(false);
        CboxBateadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxBateadoresActionPerformed(evt);
            }
        });
        jPanel1.add(CboxBateadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 210, -1));

        CboxPitchers.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        CboxPitchers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pitcher Abridor", "Pitcher de Relevos Largos", "Pitcher Cerrador" }));
        CboxPitchers.setEnabled(false);
        CboxPitchers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxPitchersActionPerformed(evt);
            }
        });
        jPanel1.add(CboxPitchers, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plantillaNuevoEquipo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 500, 460));

        jTable2.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre", "Posicion", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 450, 270));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoModoJuego.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Controller.NuevoEquipoController.eventoBotonAtras();
        Conexion con =new Conexion();
        con.BtnAtras1(txtNombreEquipo);
        con.BtnAtras2(txtNombreEquipo);
        
        ventana.getTxtNombreEquipo().setText("");
        ventana.getTxtProvincia().setText("");
        ventana.getTxtNombreJugador().setText("");
        ventana.getTxtNumeroJugador().setText("");
        
        
        
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnIngresarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarEquipoActionPerformed
        Controller.NuevoEquipoController.eventoBotonIngresarEquipo();
        Conexion con = new Conexion();
        con.IngresarEquipo(txtNombreEquipo, txtProvincia);
        
        
      
    }//GEN-LAST:event_btnIngresarEquipoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Controller.NuevoEquipoController.eventoBotonGuardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvinciaActionPerformed

    private void txtNombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreJugadorActionPerformed

    private void txtNumeroJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroJugadorActionPerformed

    private void txtNombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEquipoActionPerformed

    private void CboxPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxPosicionActionPerformed
        Controller.NuevoEquipoController.eventoCBoxPosicion();
    }//GEN-LAST:event_CboxPosicionActionPerformed

    private void CboxPitchersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxPitchersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxPitchersActionPerformed

    private void btnIngresarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarJugadorActionPerformed
        Controller.NuevoEquipoController.eventoBotonIngresarJugador();
        Conexion con =  new Conexion();
        con.IngresarJ();
        
        con.RellenarTabla2("jugadores", jTable2, ventana.getTxtNombreEquipo().getText());
        
        ventana.getTxtNombreJugador().setText("");
        ventana.getTxtNumeroJugador().setText("");
      
        
        
    }//GEN-LAST:event_btnIngresarJugadorActionPerformed

    private void CboxBateadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxBateadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxBateadoresActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String nombre = jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString();
        Conexion con =new Conexion();
        con.EliminarJug(nombre);
        con.RellenarTabla2("jugadores", jTable2, ventana.getTxtNombreEquipo().getText());
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaNuevoEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxBateadores;
    private javax.swing.JComboBox<String> CboxPitchers;
    private javax.swing.JComboBox<String> CboxPosicion;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngresarEquipo;
    private javax.swing.JButton btnIngresarJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtNombreEquipo;
    private javax.swing.JTextField txtNombreJugador;
    private javax.swing.JTextField txtNumeroJugador;
    private javax.swing.JTextField txtProvincia;
    // End of variables declaration//GEN-END:variables
}
